// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMTSnuRFNFjVxdV_72fTgnV-XH08wV7_Q',
    appId: '1:823875045545:web:db4b5889c3775fad1101b8',
    messagingSenderId: '823875045545',
    projectId: 'smart-garage-52d7c',
    authDomain: 'smart-garage-52d7c.firebaseapp.com',
    databaseURL: 'https://smart-garage-52d7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-garage-52d7c.appspot.com',
    measurementId: 'G-C6EFX2FLC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJi6sptCVjqVFi0I8azLLz6sH3FTHpq0s',
    appId: '1:823875045545:android:2461e5a908ad7c2c1101b8',
    messagingSenderId: '823875045545',
    projectId: 'smart-garage-52d7c',
    databaseURL: 'https://smart-garage-52d7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-garage-52d7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAilZ_L1iMUVsHke4Ba6ZvFjeKnAXtX9D4',
    appId: '1:823875045545:ios:4c7826f24f8c0b4d1101b8',
    messagingSenderId: '823875045545',
    projectId: 'smart-garage-52d7c',
    databaseURL: 'https://smart-garage-52d7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-garage-52d7c.appspot.com',
    iosClientId: '823875045545-p2k4s9mchcc5d8s3d6u2d1ah8hqhl5va.apps.googleusercontent.com',
    iosBundleId: 'com.example.icareMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAilZ_L1iMUVsHke4Ba6ZvFjeKnAXtX9D4',
    appId: '1:823875045545:ios:4c7826f24f8c0b4d1101b8',
    messagingSenderId: '823875045545',
    projectId: 'smart-garage-52d7c',
    databaseURL: 'https://smart-garage-52d7c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smart-garage-52d7c.appspot.com',
    iosClientId: '823875045545-p2k4s9mchcc5d8s3d6u2d1ah8hqhl5va.apps.googleusercontent.com',
    iosBundleId: 'com.example.icareMobile',
  );
}
