class IlnessText {
  IlnessText();

  GetText(int index) {
    if (index == 0) {
      return "Dementia is a term used to describe a group of symptoms that affect memory, thinking, and social abilities severely enough to interfere with daily life. It is not a specific disease, but rather a general term that describes a decline in cognitive function, including loss of memory, language, and problem-solving skills, as well as changes in mood and behavior. \n\nDementia is typically caused by damage to the brain cells, which can occur in several ways. Alzheimer's disease is the most common cause of dementia, accounting for up to 70% of cases. Other causes include vascular dementia, frontotemporal dementia, Lewy body dementia, and Parkinson's disease dementia. \n\nSymptoms of dementia can vary widely depending on the underlying cause, but may include memory loss, confusion, difficulty with communication, personality changes, and difficulty with everyday tasks such as getting dressed or cooking. There is currently no cure for dementia, but treatments and interventions can help manage symptoms and improve quality of life for those living with the condition.";
    } else if (index == 1) {
      return "Schizophrenia is a chronic and severe mental disorder that affects how a person thinks, feels, and behaves. It is a complex disorder that can be difficult to diagnose and treat, and it often has a profound impact on a person's ability to function in daily life.\n\nThe symptoms of schizophrenia can be divided into two categories: positive symptoms and negative symptoms. Positive symptoms include hallucinations (hearing or seeing things that are not there), delusions (false beliefs that are not based in reality), and disorganized speech or behavior. Negative symptoms include reduced emotional expression, lack of motivation, and social withdrawal.\n\nThe exact causes of schizophrenia are not fully understood, but it is believed to be the result of a combination of genetic, environmental, and brain chemistry factors. It often first appears in people during their late teens or early twenties, and it affects men and women equally.\n\nTreatment for schizophrenia typically involves a combination of antipsychotic medications, psychotherapy, and social support. While there is no cure for schizophrenia, with appropriate treatment, many people with the condition can manage their symptoms and lead fulfilling lives. It's essential to seek help from a mental health professional if you or a loved one is experiencing symptoms of schizophrenia.";
    } else if (index == 2) {
      return "Parkinson's disease is a chronic and progressive neurological disorder that affects movement. It is characterized by the loss of dopamine-producing brain cells in a specific part of the brain called the substantia nigra, leading to motor symptoms such as tremors, stiffness, and slowness of movement.\n\nIn addition to motor symptoms, Parkinson's disease can also cause non-motor symptoms such as depression, anxiety, sleep disturbances, and cognitive changes. The severity of symptoms and how they progress can vary widely from person to person.\n\nThe exact cause of Parkinson's disease is not fully understood, but it is believed to be a combination of genetic and environmental factors. While there is no cure for Parkinson's disease, there are several treatments available that can help manage symptoms, including medication, surgery, and lifestyle changes.\n\nThere is ongoing research to develop new treatments for Parkinson's disease, including medications that target specific pathways in the brain and gene therapies that may be able to slow or stop the progression of the disease. It is important for individuals with Parkinson's disease to work closely with a healthcare provider to develop a personalized treatment plan and to seek support from family and caregivers as needed.";
    }
  }
}
